[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/board"
  to = "/board.html"
  status = 200

[[redirects]]
  from = "/construction"
  to = "/construction.html"
  status = 200

[[redirects]]
  from = "/view/*"
  to = "/view.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/projects.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 