[build]
  publish = "."
  command = ""

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/board"
  to = "/board.html"
  status = 200

[[redirects]]
  from = "/construction"
  to = "/construction.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 